# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('upper_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_test.Department')),
            ],
        ),
    ]
